// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxfkrcvdppfusextjzss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4ZmtyY3ZkcHBmdXNleHRqenNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NDk1ODgsImV4cCI6MjA2NjEyNTU4OH0.8WmOc7wX7CIaIIxxZaJJe262pIH7AA1XOt190qtGJwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);